# Generated by Django 4.2.7 on 2023-12-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
